const express = require('express');
const { protect } = require('../middleware/auth');
const User = require('../models/User');
const router = express.Router();

// Simulate AI responses (replace with OpenAI API when ready)
const generateAIResponse = async (module, prompt) => {
  const responses = {
    chat: `**FinalX.AI Response:**\n\nThank you for your question: "${prompt}"\n\nThis is a demo response. Connect your OpenAI API key in the backend .env file to get real AI responses. I can help you with study, coding, business advice, and much more!\n\n*Powered by FinalX.AI — Ask Anything. Build Everything.*`,
    study: `**Study Assistant:**\n\nTopic: "${prompt}"\n\n📚 **Key Points:**\n• This is a demo study response\n• Add your OpenAI API key for real explanations\n• I can generate notes, Q&A, and exam tips\n\n**Practice Questions:**\n1. What is the main concept?\n2. How does this apply in real life?\n3. What are the key formulas?\n\n*Keep studying! You're doing great! 🎯*`,
    content: `**Content Generator:**\n\nFor: "${prompt}"\n\n📱 **Instagram Caption:**\n"Elevate your game. Stay ahead. ✨ #Growth #Success"\n\n🎬 **YouTube Title:**\n"The ULTIMATE Guide to ${prompt} in 2024"\n\n📘 **Facebook Post:**\n"Did you know? ${prompt} can change your life! Here's how..."\n\n#Trending #Viral #FinalXAI`,
    code: `**Code Generator:**\n\nRequest: "${prompt}"\n\n\`\`\`html\n<!DOCTYPE html>\n<html lang="en">\n<head>\n  <title>Generated by FinalX.AI</title>\n  <style>\n    body { font-family: Arial; background: #0a0a0a; color: white; }\n    h1 { color: #00f0ff; text-align: center; }\n  </style>\n</head>\n<body>\n  <h1>Hello from FinalX.AI!</h1>\n  <p>Connect OpenAI API for real code generation</p>\n</body>\n</html>\n\`\`\`\n\n*Add OpenAI API key for production-quality code!*`,
    astrology: `**🔮 Astrology Insights:**\n\nFor: "${prompt}"\n\n✨ **Today's Energy:** The stars align for new beginnings. Mercury in retrograde suggests careful communication.\n\n🌟 **Career:** Opportunities are approaching. Stay alert and trust your instincts.\n\n💚 **Health Tip:** Practice 15 minutes of meditation today. Yoga pose: Surya Namaskar.\n\n🧠 **Psychology Insight:** Your resilience is your superpower. Embrace challenges.\n\n*Note: For entertainment purposes only.*`,
    business: `**💼 Business & Income Ideas:**\n\nFor: "${prompt}"\n\n🚀 **Top 5 Income Ideas:**\n1. Freelancing on Fiverr/Upwork\n2. YouTube channel in your niche\n3. Dropshipping business\n4. Digital products (eBooks, courses)\n5. Social media management\n\n📈 **Stock Market Basics:**\n• Start with index funds (low risk)\n• Diversify your portfolio\n• Never invest money you can't afford to lose\n\n*Educational purposes only. Consult a financial advisor.*`
  };
  return responses[module] || responses.chat;
};

// AI Chat endpoint
router.post('/chat', protect, async (req, res) => {
  try {
    const { prompt, module = 'chat' } = req.body;
    if (!prompt || prompt.trim().length === 0) {
      return res.status(400).json({ message: 'Prompt is required' });
    }

    // Check usage limits for free users
    const user = req.user;
    if (!user.hasActiveSubscription() && user.usage.aiRequests >= 5) {
      return res.status(403).json({ 
        message: 'Free limit reached. Please subscribe to continue.',
        code: 'USAGE_LIMIT'
      });
    }

    // Generate response (replace with OpenAI call)
    let aiResponse = await generateAIResponse(module, prompt.trim());

    // If OpenAI key is configured, use it
    if (process.env.OPENAI_API_KEY) {
      try {
        const { OpenAI } = require('openai');
        const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
        const systemPrompts = {
          chat: 'You are FinalX.AI, a helpful all-purpose AI assistant.',
          study: 'You are a study assistant. Help students with notes, Q&A, and exam prep.',
          content: 'You are a social media content expert. Generate viral content.',
          code: 'You are an expert programmer. Generate clean, working code.',
          astrology: 'You give general wellness, astrology, and psychology insights.',
          business: 'You provide business ideas and basic financial education.'
        };
        const completion = await openai.chat.completions.create({
          model: 'gpt-3.5-turbo',
          messages: [
            { role: 'system', content: systemPrompts[module] || systemPrompts.chat },
            { role: 'user', content: prompt }
          ],
          max_tokens: 1000
        });
        aiResponse = completion.choices[0].message.content;
      } catch (openaiErr) {
        console.log('OpenAI error, using demo response');
      }
    }

    // Save to chat history & update usage
    await User.findByIdAndUpdate(user._id, {
      $push: { 
        chatHistory: { 
          module, prompt: prompt.substring(0, 500), 
          response: aiResponse.substring(0, 2000) 
        } 
      },
      $inc: { 'usage.aiRequests': 1 }
    });

    res.json({ response: aiResponse, module });
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: 'AI service error' });
  }
});

// Get chat history
router.get('/history', protect, async (req, res) => {
  try {
    const user = await User.findById(req.user._id).select('chatHistory');
    res.json({ history: user.chatHistory.slice(-50).reverse() });
  } catch (err) {
    res.status(500).json({ message: 'Server error' });
  }
});

module.exports = router;
